name: Lint

on: [push, pull_request]

env:
  # Configure pip to cache dependencies and do a user install
  PIP_NO_CACHE_DIR: false
  PIP_USER: 0
  PYTHON_VERSION: 3.9

  # Make sure package manager does not use virtualenv
  POETRY_VIRTUALENVS_CREATE: false


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: pre-commit
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Setup Poetry
        run: python -m pip install -U poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run precommit
        run: poetry run task precommit-run
